language: java
sudo: required
services:
  - docker
before_install:
  - docker build -t amarofs/demoservice -f Dockerfile .
after_success:
  - docker build -t amarofs/demoservice -f Dockerfile .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push marofs/demoservice
