language: java
sudo: required
env:
  global:
    - IMAGE_NAME=amarofs/demoservice

services:
  - docker
script:
  - docker build -t "$IMAGE_NAME" -f Dockerfile .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest
  on:
    branch: master